name: Generate Provider Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The granted-approvals repository tag to release"
        type: string
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Print params
        run: echo "Generating docs for granted-approvals tag ${GRANTED_TAG}"
        env:
          GRANTED_TAG: ${{ github.event.inputs.tag }}

      - name: Check version tag format
        run: |
          (echo "$GRANTED_TAG" | grep -Eq  ^v[0-9]+.[0-9]+.[0-9]+$) && echo "version tag matches vMAJOR.MINOR.PATCH format" || (echo "${GRANTED_TAG} did not match vMAJOR.MINOR.PATCH format (did you forget the 'v'?)" && exit 1)
        env:
          GRANTED_TAG: ${{ github.event.inputs.tag }}

      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.0"

      - name: Check Out Docs
        uses: actions/checkout@v2
        with:
          lfs: "true"
      - name: Update approvals dependency
        run: go get github.com/common-fate/granted-approvals@${{ github.event.inputs.tag }}

      - name: Generate Docs
        run: go run cmd/docscli/main.go generate --approvals-version=${{ github.event.inputs.tag }}

      - name: Open PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Provider Registry
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "update-provider-registry-${{ github.event.inputs.tag }}"
          delete-branch: true
          title: "[New Release] Generate Provider Registry for (${{ github.event.inputs.tag }}")"
          body: |
            Generated Provider Registry Setup docs for granted-approvals ${{ github.event.inputs.tag }}
          labels: |
            automated pr
